# Generated by Django 4.2.7 on 2023-11-19 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=20)),
                ('cnpj', models.IntegerField(blank=True)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
