# Generated by Django 4.2.7 on 2023-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidas',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saidas',
            name='precovenda',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
