# Generated by Django 4.2.7 on 2023-11-26 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saidas', '0004_remove_saidas_preco_remove_saidas_precovenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidas',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
